---
apiVersion: v1
kind: Namespace
metadata:
  name: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: etcd
spec:
  ports:
  - port: 2380
    name: etcd-server
  clusterIP: None
  selector:
    app: etcd
---
  apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: etcd-pdb
    namespace: etcd
  spec:
    selector:
      matchLabels:
        app: etcd
    minAvailable: 2
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: etcd
    namespace: etcd
  spec:
    serviceName: etcd-svc
    replicas: 3
    selector:
      matchLabels:
        app: etcd
    template:
      metadata:
        labels:
          app: etcd 
